dist: bionic

language: go
go:
  - "1.14"
  - master

services:
  - postgresql
  - docker

install:
  - go mod vendor
  - go get -v github.com/rubenv/sql-migrate/sql-migrate

before_script:
  - psql -c 'create database authenticator_test;' -U postgres
  - psql -c 'create database authenticator;' -U postgres
  - ls /home/travis/gopath/bin
  - (cd migrations && sql-migrate up -env="testing")
  - (cd migrations && sql-migrate up -env="development")

script:
  - go test -race ./models -test.config="../sqlboiler_test.yml"
  - go test -race -coverprofile=server.cov -covermode=atomic ./cmd/server
  - go test -race -coverprofile=verify.cov -covermode=atomic ./verify
  - (cd cmd/server && go build && ./server -config config/development.json &)
  - go test -race -coverprofile=middle.cov -covermode=atomic ./middleware

after_script:
  - bash <(curl -s https://codecov.io/bash) -f '*.cov'

before_deploy:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWD

deploy:
  - provider: script
    script: bash deploy.sh latest
    on:
      go: "1.14"
      branch: master
  - provider: script
    script: bash deploy.sh
    on:
      go: "1.14"
      tags: true
      all_branches: true
