version: '3.6'

services:
    server:
        image: moapis/authenticator-server:master
        build: 
            dockerfile: server.Dockerfile
            context: .

    admin:
        image: moapis/authenticator-admin:master
        build: 
            dockerfile: admin.Dockerfile
            context: .
    
    migrations:
        image: moapis/authenticator-migrations:master
        build:
            dockerfile: Dockerfile
            context: migrations