// Copyright (c) 2019, Mohlmann Solutions SRL. All rights reserved.
// Use of this source code is governed by a License that can be found in the LICENSE file.
// SPDX-License-Identifier: BSD-3-Clause

/*
Package verify provides middleware for GRPc servers which need
to verify JSON Web Tokens generated by this Authenticator service.
*/
package verify

import (
	"encoding/base64"
	"errors"
	"reflect"
	"testing"
)

func TestParseJWTHeader(t *testing.T) {
	tests := []struct {
		name    string
		token   string
		want    int
		wantErr bool
	}{
		{
			"base64 error",
			"2",
			0,
			true,
		},
		{
			"Unmarshal error",
			"",
			0,
			true,
		},
		{
			"algoritm error",
			base64.RawURLEncoding.EncodeToString([]byte("{\"Alg\": \"foo\"}")),
			0,
			true,
		},
		{
			"ParseInt error",
			base64.RawURLEncoding.EncodeToString([]byte("{\"Alg\": \"EdDSA\", \"Kid\": \"x\"}")),
			0,
			true,
		},
		{
			"Valid header",
			base64.RawURLEncoding.EncodeToString([]byte("{\"Alg\": \"EdDSA\", \"Kid\": \"10\"}")),
			10,
			false,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := ParseJWTHeader(tt.token)
			if (err != nil) != tt.wantErr {
				t.Errorf("ParseJWTHeader() error = %v, wantErr %v", err, tt.wantErr)
				return
			}
			var e *VerificationErr
			if tt.wantErr && !errors.As(err, &e) {
				t.Errorf("ParseJWTHeader() error = %T, wantErr %T", err, e)
			}
			if got != tt.want {
				t.Errorf("ParseJWTHeader() = %v, want %v", got, tt.want)
			}
		})
	}
}

func TestVerificator_get(t *testing.T) {
	key := []byte("foobar")
	keys := map[int32][]byte{10: key}

	tests := []struct {
		name    string
		keys    map[int32][]byte
		kid     int32
		wantKey []byte
		wantOk  bool
	}{
		{
			"Empty map",
			nil,
			33,
			nil,
			false,
		},
		{
			"Existing key",
			keys,
			10,
			key,
			true,
		},
		{
			"Non-existing key",
			keys,
			33,
			nil,
			false,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			v := &Verificator{
				keys: tt.keys,
			}
			gotKey, gotOk := v.get(tt.kid)
			if !reflect.DeepEqual(gotKey, tt.wantKey) {
				t.Errorf("Verificator.get() gotKey = %v, want %v", gotKey, tt.wantKey)
			}
			if gotOk != tt.wantOk {
				t.Errorf("Verificator.get() gotOk = %v, want %v", gotOk, tt.wantOk)
			}
		})
	}
}

func TestVerificator_set(t *testing.T) {
	type args struct {
		kid int32
		key []byte
	}
	tests := []struct {
		name string
		keys map[int32][]byte
		args args
		want map[int32][]byte
	}{
		{
			"Nil map",
			nil,
			args{10, []byte("foobar")},
			map[int32][]byte{10: []byte("foobar")},
		},
		{
			"extra key",
			map[int32][]byte{10: []byte("foobar")},
			args{22, []byte("hello")},
			map[int32][]byte{10: []byte("foobar"), 22: []byte("hello")},
		},
		{
			"existing key",
			map[int32][]byte{10: []byte("foobar")},
			args{10, []byte("hello")},
			map[int32][]byte{10: []byte("hello")},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			v := &Verificator{
				keys: tt.keys,
			}
			v.set(tt.args.kid, tt.args.key)
			if !reflect.DeepEqual(v.keys, tt.want) {
				t.Errorf("Verificator.set() v.keys = %v, want %v", v.keys, tt.want)
			}
		})
	}
}
