// Code generated by SQLBoiler 3.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Audiences     string
	Groups        string
	JWTKeys       string
	Migrations    string
	Passwords     string
	UserAudiences string
	UserGroups    string
	Users         string
}{
	Audiences:     "audiences",
	Groups:        "groups",
	JWTKeys:       "jwt_keys",
	Migrations:    "migrations",
	Passwords:     "passwords",
	UserAudiences: "user_audiences",
	UserGroups:    "user_groups",
	Users:         "users",
}
