// Code generated by SQLBoiler 4.1.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Audiences", testAudiencesUpsert)

	t.Run("Groups", testGroupsUpsert)

	t.Run("JWTKeys", testJWTKeysUpsert)

	t.Run("Passwords", testPasswordsUpsert)

	t.Run("Users", testUsersUpsert)
}
